#!/bin/bash -e

WORKSPACE=`fd package\.json packages/* -x cat | jq '.name' | tr -d '"' | fzf --prompt="Area: "`
SCRIPT=`fd package\.json packages/* -x cat | jq '. | select(.name as \$tmpvar | ["'${WORKSPACE}'"] | index(\$tmpvar) ) | .scripts | keys | .[]' | tr -d '"' | fzf --prompt="Script to run: "`

write_noline() {
  osascript -e "tell application \"iTerm2\" to tell current window to tell current session to write text \"${@}\" newline NO"
}

write_noline "npm --workspace ${WORKSPACE} run ${SCRIPT}"
