#!/bin/bash -e

# --preview="echo {}"

CONTEXT="--context "`yq '.contexts.[].name' < ~/.kube/config | fzf --prompt="Context: "`

# NAMESPACE="--namespace ac-steam"
NAMESPACE="--namespace "`kubectl ${CONTEXT} get namespace -o custom-columns=name:.metadata.name | fzf --prompt="Namespace: "`

# tr ' ' '\n'
COMMANDS=(
    'restart-deployment'
    'get deployments.app -o wide -w'
    'get secrets -o wide'
    'get configmaps -o json'
    'create job'
    'delete'
    'exec'
    'annotate'
    'apply -f'
    'logs'
)
CMD=''
for i in ${!COMMANDS[@]}; do
    CMD="${COMMANDS[$i]}|$CMD"
done
KCMD=`echo $CMD  | sed 's/|*$//g' | tr '|' '\n' | fzf --prompt="Command: "`
if [ "${KCMD}" == "exec" ]; then
    POD=`kubectl ${NAMESPACE} ${CONTEXT} get pods -o custom-columns=name:.metadata.name,status:.status.phase | fzf | sed 's/ .*$//g'`

    CONTAINER="--container "`kubectl ${NAMESPACE} ${CONTEXT} get pods ${POD} -o custom-columns=containers:.spec.containers\[\*\].name | tail -n1 | tr ',' '\n' | fzf --prompt="Container: "`

    KCMD="${KCMD} ${POD} ${CONTAINER} -it -- /bin/sh"
fi
if [ "${KCMD}" == "annotate" ]; then
    RESOURCE=`kubectl api-resources -o name | fzf --prompt="Resource: "`
    POD=`kubectl ${CONTEXT} ${NAMESPACE} get ${RESOURCE} -o custom-columns=name:.metadata.name,status:.status.phase | fzf | sed 's/ .*$//g'`

    KCMD="${KCMD} ${RESOURCE} ${POD} kustomize.toolkit.fluxcd.io/reconcile='disabled'"
fi

if [ "${KCMD}" == "delete" ]; then
    RESOURCE=`kubectl api-resources -o name | fzf --prompt="Resource: "`

    KCMD="${KCMD} ${RESOURCE} "
fi

if [ "${KCMD}" == "restart-deployment" ]; then
    DEPLOYMENTS=`kubectl --namespace ac-steam --context bcp-nmacs-stage get deployments.apps -o custom-columns=name:.metadata.name | fzf --prompt="Deployments: "`
    KCMD="rollout restart deployment ${DEPLOYMENTS}"
fi

if [ "${KCMD}" == "logs" ]; then
    POD=`kubectl ${NAMESPACE} ${CONTEXT} get pods -o custom-columns=name:.metadata.name,status:.status.phase | fzf | sed 's/ .*$//g'`

    CONTAINER="--container "`kubectl ${NAMESPACE} ${CONTEXT} get pods ${POD} -o custom-columns=containers:.spec.containers\[\*\].name | tail -n1 | tr ',' '\n' | fzf --prompt="Container: "`

    KCMD="${KCMD} ${POD} ${CONTAINER} --since=5m -f"
fi
if [ "${KCMD}" == "create job" ]; then
    JOB="--from="`kubectl ${NAMESPACE} ${CONTEXT} get cronjobs.batch -o name | fzf --prompt="Cronjob: "`

    KCMD="${KCMD} ${JOB} "
fi


write_noline() {
  osascript -e "tell application \"iTerm2\" to tell current window to tell current session to write text \"${@}\" newline NO"
}

write_noline "kubectl ${NAMESPACE} ${CONTEXT} ${KCMD} "
