#!/bin/bash -e

REPO=`git config --get remote.origin.url`
REPO=${REPO#*github.com:}
REPO=${REPO%.git}
PR=`gh pr list -R ${REPO} | fzf | cut -d$'\t' -f 1`

TO_DISMISS=$(gh api --method GET repos/${REPO}/pulls/${PR}/reviews --jq '.[] | {user: .user.login, id: .id, state: .state}' | fzf --no-sort --tac | jq '.id')

read -p "Enter Dismiss-Message: " MESSAGE

gh api repos/${REPO}/pulls/${PR}/reviews/${TO_DISMISS}/dismissals --method PUT -f message=${MESSAGE}

