#!/bin/bash -e
FILE=~/.local/share/nvim/maorun-time.json

DATA=`cat $FILE`
WEEKDAY=`date +"%A"`
WEEKNUMBER=`date +"%W"`
LASTWEEK=$((WEEKNUMBER-1))

JQ_EXPRESSION='.data["2023"]["'${WEEKNUMBER}'"]["weekdays"]["'${WEEKDAY}'"]["summary"]'
VALUE=`echo $DATA | jq $JQ_EXPRESSION`
# VALUE_ROUND=`echo $VALUE | tr '.' ',' | awk  '{ print sprintf("%.2f", $1); }'`
# echo $VALUE_ROUND

OVERHOUR_WEEK=`echo $DATA | jq '.data["2023"]["'${WEEKNUMBER}'"]["summary"].overhour'`
OVERHOUR_MONDAY=``
getOverview() {
    echo $DATA | jq '.data["2023"]["'${WEEKNUMBER}'"]["weekdays"]["'${1}'"]["summary"].overhour' 2> /dev/null
    echo "\t"
    echo $DATA | jq '.data["2023"]["'${WEEKNUMBER}'"].weekdays.'${1}'.items[] | "\t\(.startReadable)-\(.endReadable)"' 2> /dev/null
}

echo -e "letzte Woche Gesammtüberstunden:\t " $(echo $DATA | jq '.data["2023"]["'${LASTWEEK}'"]["summary"].overhour')
echo -e "Gesammtüberstunden:\t [`echo $DATA | jq '.hoursPerWeekday | add' `]" $OVERHOUR_WEEK
echo -e "Montag:\t\t [`echo $DATA | jq '.hoursPerWeekday.Montag' `]" $(getOverview "Montag")
echo -e "Dienstag:\t [`echo $DATA | jq '.hoursPerWeekday.Dienstag' `]" $(getOverview "Dienstag")
echo -e "Mittwoch:\t [`echo $DATA | jq '.hoursPerWeekday.Mittwoch' `]" $(getOverview "Mittwoch")
echo -e "Donnerstag:\t [`echo $DATA | jq '.hoursPerWeekday.Donnerstag' `]" $(getOverview "Donnerstag")
echo -e "Freitag:\t [`echo $DATA | jq '.hoursPerWeekday.Freitag' `]" $(getOverview "Freitag")

echo -e "\n"
echo -e "Week-Number: $WEEKNUMBER"
IS_PAUSED=`echo $DATA | jq '.paused'`
if [ $IS_PAUSED = "true" ]; then
    IS_PAUSED="[paused]"
else
    IS_PAUSED=""
fi

echo -e "Today: "$IS_PAUSED
echo $DATA | jq '.data["2023"]["'${WEEKNUMBER}'"].weekdays.'${WEEKDAY}'.items[] | "Start: \(.startReadable) Uhr, End: \(.endReadable) Uhr, Diff: \(.diffInHours)"'

# say "$VALUE_ROUND Stunden"

