#!/bin/bash -e
FILE=~/.local/share/nvim/maorun-time.json

DATA=`cat $FILE`
WEEKDAY=`date +"%A"`
WEEKNUMBER=`date +"%W"`

JQ_EXPRESSION='.data["2023"]["'${WEEKNUMBER}'"]["weekdays"]["'${WEEKDAY}'"]["summary"]'
VALUE=`echo $DATA | jq $JQ_EXPRESSION`
# VALUE_ROUND=`echo $VALUE | tr '.' ',' | awk  '{ print sprintf("%.2f", $1); }'`
# echo $VALUE_ROUND

OVERHOUR_WEEK=`echo $DATA | jq '.data["2023"]["'${WEEKNUMBER}'"]["summary"].overhour'`
OVERHOUR_MONDAY=``
getOverview() {
    echo $DATA | jq '.data["2023"]["'${WEEKNUMBER}'"]["weekdays"]["'${1}'"]["summary"].overhour' 2> /dev/null
    echo "\t"
    echo $DATA | jq '.data["2023"]["'${WEEKNUMBER}'"].weekdays.'${1}'.items[] | "\t\(.startReadable)-\(.endReadable)"' 2> /dev/null
}

echo -e "Gesammtüberstunden:\t" $OVERHOUR_WEEK
echo -e "Montag:\t\t" $(getOverview "Montag")
echo -e "Dienstag:\t" $(getOverview "Dienstag")
echo -e "Mittwoch:\t" $(getOverview "Mittwoch")
echo -e "Donnerstag:\t" $(getOverview "Donnerstag")
echo -e "Freitag:\t" $(getOverview "Freitag")

echo -e "\n"
echo -e "Week-Number: $WEEKNUMBER"
echo -e "Today:"
echo $DATA | jq '.data["2023"]["'${WEEKNUMBER}'"].weekdays.'${WEEKDAY}'.items[] | "Start: \(.startReadable) Uhr, End: \(.endReadable) Uhr, Diff: \(.diffInHours)"'

# say "$VALUE_ROUND Stunden"

