_node_complete() {
  local cur_word options
  cur_word="${COMP_WORDS[COMP_CWORD]}"
  if [[ "${cur_word}" == -* ]] ; then
    COMPREPLY=( $(compgen -W '--track-heap-objects --interpreted-frames-native-stack --inspect-brk --test --max-old-space-size --global-search-paths --trace-exit --disallow-code-generation-from-strings --experimental-json-modules --addons --watch-path --test-name-pattern --stack-trace-limit --debug-brk --experimental-repl-await --check --trace-tls --jitless --heapsnapshot-near-heap-limit --watch --experimental-top-level-await --tls-keylog --abort-on-uncaught-exception --require --verify-base-objects --diagnostic-dir --inspect-port --prof --unhandled-rejections --inspect-brk-node --extra-info-on-fatal-exception --report-uncaught-exception --print --trace-sync-io --test-udp-no-try-send --test-only --tls-min-v1.3 --redirect-warnings --tls-min-v1.0 --heap-prof-interval --perf-basic-prof --perf-basic-prof-only-functions --cpu-prof --perf-prof --experimental-network-imports --max-http-header-size --report-on-signal --throw-deprecation --prof-process --v8-options --force-context-aware --napi-modules --warnings --trace-atomics-wait --deprecation --cpu-prof-interval --heap-prof --force-fips --pending-deprecation --input-type --tls-max-v1.2 --interactive --experimental-global-customevent --preserve-symlinks-main --perf-prof-unwinding-info --cpu-prof-dir --heap-prof-name --policy-integrity --expose-internals --trace-warnings --update-assert-snapshot --experimental-report --trace-event-file-pattern --trace-uncaught --experimental-loader --http-parser --heapsnapshot-signal --inspect --node-memory-debug --inspect-publish-uid --experimental-wasm-modules --experimental-modules --report-signal --debug --eval --tls-min-v1.1 --report-filename --experimental-global-webcrypto --trace-event-categories --experimental-worker --heap-prof-dir --experimental-fetch --enable-fips --preserve-symlinks --force-node-api-uncaught-exceptions-policy --dns-result-order --trace-sigint --secure-heap-min --experimental-policy --experimental-import-meta-resolve --use-largepages --openssl-legacy-provider --zero-fill-buffers --report-dir --use-bundled-ca --enable-source-maps --insecure-http-parser --use-openssl-ca --openssl-config --icu-data-dir --build-snapshot --v8-pool-size --report-on-fatalerror --secure-heap --experimental-specifier-resolution --trace-deprecation --report-compact --experimental-vm-modules --version --force-async-hooks-checks --frozen-intrinsics --completion-bash --help --tls-min-v1.2 --tls-max-v1.3 --title --cpu-prof-name --huge-max-old-generation-size --disable-proto --security-revert --tls-cipher-list --node-snapshot --debug-arraybuffer-allocations --conditions --openssl-shared-config --experimental-wasi-unstable-preview1 --experimental-abortcontroller --snapshot-blob --debug-port -p -pe --inspect-brk-node= --inspect= --print <arg> -e -c --es-module-specifier-resolution --prof-process -C --debug-brk= --loader --debug= --report-directory --inspect-brk= -v -h -i --security-reverts -r --trace-events-enabled' -- "${cur_word}") )
    return 0
  else
    COMPREPLY=( $(compgen -f "${cur_word}") )
    return 0
  fi
}
complete -o filenames -o nospace -o bashdefault -F _node_complete node node_g
